# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/comment/add
Content-Type: application/json

{
  "userId": "aaa",
  "content": "A Test 1"
}

###

GET http://localhost:8080/comment/view/1
Accept: application/json

###

GET http://localhost:8080/comment/viewbyuserid/aaa
Accept: application/json

###

GET http://localhost:8080/comment/list
Accept: application/json

###

PUT http://localhost:8080/comment/update/1
Content-Type: application/json

{
  "userId": "aaaa",
  "content": "A Test update"
}

###

DELETE http://localhost:8080/comment/delete/1
Accept: application/json

###