# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/user/add
Content-Type: application/json

{
  "id": "2001_hcy",
  "password": "a123123",
  "username": "허찬영",
  "email": "2001_hcy@naver.com"
}

###

GET http://localhost:8080/user/view/1
Accept: application/json

###

GET http://localhost:8080/user/list
Accept: application/json

###

PUT http://localhost:8080/user/update/4
Content-Type: application/json

{
  "username": "ccc",
  "email": "ccc@dgsw",
  "profileImagePath": "/profiles/2019/04/04/test.png",
  "profileImageName": "default.jpg"
}

###

DELETE http://localhost:8080/user/delete/2
Accept: application/json

###

POST http://localhost:8080/attachment
Content-Type: application/json
